### ISSUE TITLE
Something went wrong contacting the API

### ISSUE THREAD

**Issue by hassuser** [fredrikbaberg/hassio-addons#288]
After the lates  HA update 2022.8 I get multiple errors starting with

 [19:06:01] ERROR: Something went wrong contacting the API

Then is

2022-08-25 19:10:21,841 - octoprint.plugin.core - ERROR - There was an error loading plugin discovery
Traceback (most recent call last):
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 1519, in load_plugin
    plugin.load()
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/plugins/discovery/__init__.py", line 38, in __plugin_load__
    plugin = DiscoveryPlugin()
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/plugins/discovery/__init__.py", line 73, in __init__
    self._zeroconf = zeroconf.Zeroconf()
  File "/data/python/octoprint/lib/python3.9/site-packages/zeroconf/_core.py", line 381, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
  File "/data/python/octoprint/lib/python3.9/site-packages/zeroconf/_utils/net.py", line 344, in create_sockets
    listen_socket = new_socket(ip_version=ip_version, apple_p2p=apple_p2p, bind_addr=('',))
  File "/data/python/octoprint/lib/python3.9/site-packages/zeroconf/_utils/net.py", line 228, in new_socket
    s = socket.socket(socket_family, socket.SOCK_DGRAM)
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied
2022-08-25 19:10:21,894 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 34 hook handlers
2022-08-25 19:10:21,930 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2022-08-25 19:10:21,934 - octoprint.cli.server - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/data/python/octoprint/bin/octoprint", line 8, in <module>
    sys.exit(main())
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/__init__.py", line 965, in main
    octo(args=args, prog_name="octoprint", auto_envvar_prefix="OCTOPRINT")
  File "/data/python/octoprint/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/python/octoprint/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/python/octoprint/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/python/octoprint/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/python/octoprint/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/python/octoprint/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/cli/server.py", line 317, in serve_command
    run_server(
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/cli/server.py", line 164, in run_server
    octoprint_server.run()
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/server/__init__.py", line 371, in run
    self._start_intermediary_server()
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/server/__init__.py", line 2468, in _start_intermediary_server
    self._intermediary_server = ServerClass(
  File "/usr/lib/python3.9/socketserver.py", line 448, in __init__
    self.socket = socket.socket(self.address_family,
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied
[19:10:22] INFO: Starting octoprint...
[19:10:22] INFO: Starting proxy...
{"level":"info","ts":1661447422.3143153,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
{"level":"warn","ts":1661447422.31669,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":5}
run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: socket: permission denied

Already uninstalled the add on restarted HA and installed it back. CPU and RAM goes to over 60% when i start the add-on and can't access the  web ui. Other than updating HA i haven't changed anything in Octoprint as i have not printed for more than a month for work reasons

**Comment by fredrikbaberg** [comment]
Please state:
- Addon name
- Addon version
- Platform
- OS

**Comment by hassuser** [comment]
3DPrinter
Current version: 2021.11.7
Home Assistant 2022.8.7
Supervisor 2022.08.3

**Comment by fredrikbaberg** [comment]
What platform are you using?
I can't replicate the issue on "Virtual Machine / ova" or "Raspberry Pi 3 / rpi3-64", both are using Home Assistant Operating System 8.5.

**Comment by hassuser** [comment]
I’m using it on debian 11 supervised. I have tested it on a vm and it works
fine, but I can’t have that pc running ha on the vm, maybe it’s related to
devian itself ¯\_(ツ)_/¯

**Comment by hassuser** [comment]
Never Mind, problem was with the Debian 11 supervised install.
