### ISSUE TITLE
Can't upgrade to current from fresh install under HomeAssistant

### ISSUE THREAD

**Issue by somedesa** [fredrikbaberg/hassio-addons#292]
Hi,

New version hosed functioning install.

I've searched for these errors and tried to install Argon separately to no avail.

> `ImportError: Error loading shared library /tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-arm-linux-musleabihf.so: Operation not permitted`

> ERROR: Could not find a version that satisfies the requirement argon2-cffi-bindings (from argon2-cffi) (from versions: 21.1.0, 21.2.0)
> ERROR: No matching distribution found for argon2-cffi-bindings

I'd been running the add-on for a long time.  Wouldn't upgrade to new 1.86.  Uninstalled.  Rebooted server.  Install goes fine from add-on store of 1.7x.  Upgrade wizard to 1.86 produces below output.

No idea what to try next.

TIA,
Dennis

Updating, please wait.
/data/python/octoprint/bin/python -m pip --disable-pip-version-check install https://github.com/OctoPrint/OctoPrint/archive/1.8.6.zip --no-cache-dir
Collecting https://github.com/OctoPrint/OctoPrint/archive/1.8.6.zip
Downloading https://github.com/OctoPrint/OctoPrint/archive/1.8.6.zip (6.6 MB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (2021.2.23)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.10.11 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (2021.10.11)
Collecting OctoPrint-PiSupport>=2022.3.28
Downloading OctoPrint_PiSupport-2022.6.13-py2.py3-none-any.whl (33 kB)
Collecting argon2_cffi<22,>=21.3.0
Downloading argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting cachelib<0.3,>=0.2
Downloading cachelib-0.2.0-py3-none-any.whl (12 kB)
Collecting Click<9,>=8.0.3
Downloading click-8.1.3-py3-none-any.whl (96 kB)
Collecting colorlog<7,>=6
Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: emoji<2,>=1.4.2 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (1.6.1)
Requirement already satisfied: feedparser<7,>=6.0.8 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (6.0.8)
Requirement already satisfied: filetype<2,>=1.0.7 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (1.0.8)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (2.0)
Collecting Flask-Babel<3,>=2.0
Downloading Flask_Babel-2.0.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (0.5.0)
Collecting Flask-Limiter<3,>=2.6
Downloading Flask_Limiter-2.7.0-py3-none-any.whl (25 kB)
Collecting flask<2.2,>=2.1
Downloading Flask-2.1.3-py3-none-any.whl (95 kB)
Collecting frozendict<3,>=2.0
Downloading frozendict-2.3.4-py3-none-any.whl (11 kB)
Requirement already satisfied: future<1,>=0.18.2 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (0.18.2)
Collecting markdown<4,>=3.2.2
Downloading Markdown-3.4.1-py3-none-any.whl (93 kB)
Requirement already satisfied: netaddr<0.9,>=0.8 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (0.8.0)
Requirement already satisfied: netifaces<1,>=0.11 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (0.11.0)
Collecting passlib<2,>=1.7.4
Downloading passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Requirement already satisfied: pathvalidate<3,>=2.4.1 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (2.5.0)
Requirement already satisfied: pkginfo<2,>=1.7.1 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (1.8.1)
Requirement already satisfied: psutil<6,>=5.8 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (5.8.0)
Requirement already satisfied: pylru<2,>=1.2 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (1.2.0)
Requirement already satisfied: pyserial<4,>=3.4 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (3.5)
Requirement already satisfied: PyYAML<6,>=5.4.1 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (5.4.1)
Requirement already satisfied: requests<3,>=2.26.0 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (2.26.0)
Requirement already satisfied: sarge==0.1.6 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (0.1.6)
Requirement already satisfied: semantic_version<3,>=2.8.5 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (2.8.5)
Collecting sentry-sdk<2,>=1.5.7
Downloading sentry_sdk-1.10.1-py2.py3-none-any.whl (166 kB)
Requirement already satisfied: tornado<7,>=6.0.4 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (6.1)
Collecting watchdog<2,>=1
Downloading watchdog-1.0.2.tar.gz (98 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting websocket-client<2,>=1.2.1
Downloading websocket_client-1.4.1-py3-none-any.whl (55 kB)
Collecting werkzeug<2.1,>=2.0
Downloading Werkzeug-2.0.3-py3-none-any.whl (289 kB)
Collecting wrapt<1.14,>=1.13.3
Downloading wrapt-1.13.3.tar.gz (48 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: zeroconf<0.34,>=0.33 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (0.33.4)
Collecting zipstream-ng<2.0.0,>=1.3.4
Downloading zipstream-ng-1.3.4.tar.gz (22 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: blinker<2,>=1.4 in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (1.4)
Requirement already satisfied: regex in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (2021.11.10)
Requirement already satisfied: unidecode in /data/python/octoprint/lib/python3.9/site-packages (from OctoPrint==1.8.6) (1.3.2)
Collecting argon2-cffi-bindings
Downloading argon2-cffi-bindings-21.2.0.tar.gz (1.8 MB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'error'
Downloading argon2-cffi-bindings-21.1.0.tar.gz (1.8 MB)
ERROR: Command errored out with exit status 1:
command: /data/python/octoprint/bin/python /data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp_y26evld
cwd: /tmp/pip-install-kppv7v7q/argon2-cffi-bindings_0da7d4e4ceba443da685b3cc8a1ce78a
Complete output (35 lines):
Traceback (most recent call last):
File "/data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
main()
File "/data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
return hook(metadata_directory, config_settings)
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
self.run_setup()
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
exec(code, locals())
File "<string>", line 86, in <module>
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
return distutils.core.setup(**attrs)
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
_setup_distribution = dist = klass(attrs)
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 476, in __init__
_Distribution.__init__(
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
self.finalize_options()
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 900, in finalize_options
ep(self)
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
ep.load()(self, ep.name, value)
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
add_cffi_module(dist, cffi_module)
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
execfile(build_file_name, mod_vars)
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
exec(code, glob, glob)
File "src/_argon2_cffi_bindings/_ffi_build.py", line 44, in <module>
ffi = FFI()
File "/tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/cffi/api.py", line 48, in __init__
import _cffi_backend as backend
ImportError: Error loading shared library /tmp/pip-build-env-06mf746_/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-arm-linux-musleabihf.so: Operation not permitted
----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b9/e9/184b8ccce6683b0aa2fbb7ba5683ea4b9c5763f1356347f1312c32e3c66e/argon2-cffi-bindings-21.2.0.tar.gz#sha256=bb89ceffa6c791807d1305ceb77dbfacc5aa499891d2c55661c6459651fc39e3 (from https://pypi.org/simple/argon2-cffi-bindings/) (requires-python:>=3.6). Command errored out with exit status 1: /data/python/octoprint/bin/python /data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp_y26evld Check the logs for full command output.
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'error'
INFO: pip is looking at multiple versions of sarge to determine which version is compatible with other requirements. This could take a while.
Collecting sarge==0.1.6
Downloading sarge-0.1.6.tar.gz (26 kB)
Preparing metadata (setup.py): started
ERROR: Command errored out with exit status 1:
command: /data/python/octoprint/bin/python /data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpe5s9yoz6
cwd: /tmp/pip-install-kppv7v7q/argon2-cffi-bindings_4cefcd4155464446b07df72ab513e306
Complete output (35 lines):
Traceback (most recent call last):
File "/data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
main()
File "/data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
return hook(metadata_directory, config_settings)
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
self.run_setup()
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
exec(code, locals())
File "<string>", line 333, in <module>
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
return distutils.core.setup(**attrs)
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
_setup_distribution = dist = klass(attrs)
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 476, in __init__
_Distribution.__init__(
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
self.finalize_options()
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 900, in finalize_options
ep(self)
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
ep.load()(self, ep.name, value)
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
add_cffi_module(dist, cffi_module)
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
execfile(build_file_name, mod_vars)
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
exec(code, glob, glob)
File "src/_argon2_cffi_bindings/_ffi_build.py", line 14, in <module>
ffi = FFI()
File "/tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/cffi/api.py", line 48, in __init__
import _cffi_backend as backend
ImportError: Error loading shared library /tmp/pip-build-env-oy92e73t/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-arm-linux-musleabihf.so: Operation not permitted
----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/fe/c7/1796c08bc2834424326bec6fffb81bd082cb6c78b278fd0a55b2a09b0454/argon2-cffi-bindings-21.1.0.tar.gz#sha256=5b3c72b092761e9aa8a8335096c409e9d68d127ae64520848d1d9d47459c4650 (from https://pypi.org/simple/argon2-cffi-bindings/) (requires-python:>=3.6). Command errored out with exit status 1: /data/python/octoprint/bin/python /data/python/octoprint/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpe5s9yoz6 Check the logs for full command output.
Preparing metadata (setup.py): finished with status 'done'
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of octoprint to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement argon2-cffi-bindings (from argon2-cffi) (from versions: 21.1.0, 21.2.0)
ERROR: No matching distribution found for argon2-cffi-bindings
The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.

**Comment by fredrikbaberg** [comment]
Before attempting to upgrade you may want to consider #29, login through Ingress breaks with the later versions of OctoPrint (1.8.3 and newer) and I still don't have a solution to this.

What hardware and architecture are you running on? I can update from a clean install on my VM (amd64).

**Comment by fredrikbaberg** [comment]
I'll close this due to no reply.
